# Generated by Django 2.2.7 on 2019-11-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_case', models.CharField(max_length=40)),
                ('complete_case', models.BooleanField(default=False)),
            ],
        ),
    ]
